# Generated by Django 2.0.3 on 2018-05-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_tags'),
        ('notifications', '0002_auto_20180521_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
